title: Disorientations Docs
email: gro.snoitatneirosid@disorientations.org
description: >-
  An informal archive of 100+ disorientation publications by student activists, threading counter-narratives across institutions.
twitter_username: diso_archive
github_username: disorientations

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag