title: Disorientations Docs
email: gro.snoitatneirosid@disorientations.org
description: >-
  An informal archive of 100+ disorientation publications by student activists, threading counter-narratives across institutions.
twitter_username: diso_archive
github_username: disorientations

collections:
  docs:
    output: true
    permalink: /:title

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

titles_from_headings:
  enabled:     true
  strip_title: false
  collections: true

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-titles-from-headings
